version: '3.8'

services:
  postgres-orders:
    container_name: graphql-orders-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: graphql-orders-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d graphql-orders-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microbuy-network

  orders-service:
    container_name: orders-service
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "npx prisma generate && npm run start:dev"]
    volumes:
      - ./:/usr/src/app
    ports:
      - 3334:3334
    depends_on:
      postgres-orders:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - microbuy-network

networks:
  microbuy-network:
    external: true